language: python

python:
  - "3.5"
  - "3.6"

# TODO: remove these overrides once default dist supports python 3.7
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - "pip install flake8 futures mock psycopg2 pylint pytest requests"

script:
  - "make flake8"
  - "make pylint"
  - "make unittest"

sudo: false

addons:
  apt:
    packages:
      - postgresql-9.4
