language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - "pip install flake8 futures mock psycopg2 pylint pytest requests"

script:
  - "make flake8"
  - "make pylint"
  - "make unittest"

sudo: false

addons:
  apt:
    packages:
      - postgresql-9.4
