language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

install:
  - "pip install pylint==1.3.1 pytest mock psycopg2 requests"

script:
  - "(python -V 2>&1 | grep -qF 'Python 2.6') || make pylint"
  - "make unittest"
