language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

install:
  - "pip install pylint pytest mock pep8 psycopg2 requests futures"

script:
  - "make pylint"
  - "make pep8"
  - "make unittest"

sudo: false
