[book]
title = "pglookout"
authors = ["Aiven developers"]
description = "PostgreSQL replication monitoring and failover daemon"
src = "docs"
language = "en"

[build]
build-dir = "book"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/aiven/pglookout"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/aiven/pglookout/edit/main/{path}"
