[tool.black]
line-length = 125

[tool.isort]
no_sections = true
force_alphabetical_sort = true
combine_as_imports = true
profile = "black"
skip_gitignore = true
line_length = 125

[tool.pytest.ini_options]
python_classes = "!TestPG"  # Ignore class named `TestPG`.
testpaths = 'test/'
addopts = '-vv'

[tool.flake8]
ignore = [
    'E722',  # https://www.flake8rules.com/rules/E722.html Do not use bare except, specify exception instead
    'E203',  # https://www.flake8rules.com/rules/E203.html Whitespace before ':'
    'W503',  # https://www.flake8rules.com/rules/W503.html Line break occurred before a binary operator
]
max-line-length = 125

[tool.mypy]
strict = true
files = [
    'pglookout/',
    'test/',
    './*.py',
]

[tool.pylint.'MESSAGES CONTROL']
enable = [
    'useless-suppression',
]
disable = [
    'duplicate-code',
    'fixme',
    'invalid-name',
    'missing-docstring',
    'too-many-branches',
    'too-many-instance-attributes',
    'too-many-locals',
    'too-many-statements',
    'wrong-import-order',
]

[tool.pylint.'FORMAT']
max-line-length = 125
max-module-lines = 1200

[tool.pylint.'REPORTS']
output-format = 'text'
reports = 'no'

[tool.pylint.'TYPECHECK']
extension-pkg-whitelist = 'pydantic'

[tool.pylint.'DESIGN']
max-args = 10
max-attributes = 10
